#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

key=$(ynh_string_random --length=30)

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Client for synchronizing online media" --log="/var/log/$app/$app.log"

usermod -a -G ssl-cert $app

#=================================================
# INSTALL DODOC
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
#	rm package-lock.json
  chmod +x postinstall.sh
  chmod +x ./bin/build-player.js
 	ynh_hide_warnings ynh_exec_as_app npm install
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Server up and running"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
